# Generated by Django 5.1.5 on 2025-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Jake and Jill', max_length=50),
            preserve_default=False,
        ),
    ]
